#include "Bytecode.h"
#include <sstream>
#include <unordered_set>
namespace jspp {
static bool expression(const Expr&e,Bytecode&b,std::string&error){auto emit=[&](Op op){b.instructions.push_back({op});};switch(e.kind){case ExprKind::Number:b.instructions.push_back({Op::PushNumber,e.number});return true;case ExprKind::String:b.instructions.push_back({Op::PushString,0,false,e.text});return true;case ExprKind::Boolean:b.instructions.push_back({Op::PushBoolean,0,e.text=="true"});return true;case ExprKind::Null:emit(Op::PushNull);return true;case ExprKind::Undefined:emit(Op::PushUndefined);return true;case ExprKind::Identifier:b.instructions.push_back({Op::Load,0,false,e.text});return true;case ExprKind::Unary:if(!expression(*e.right,b,error))return false;if(e.text=="+")emit(Op::UnaryPlus);else if(e.text=="-")emit(Op::Negate);else emit(Op::Not);return true;case ExprKind::Binary:break;}if(!expression(*e.left,b,error)||!expression(*e.right,b,error))return false;const auto&o=e.text;if(o=="+")emit(Op::Add);else if(o=="-")emit(Op::Subtract);else if(o=="*")emit(Op::Multiply);else if(o=="/")emit(Op::Divide);else if(o=="%")emit(Op::Remainder);else if(o=="==")emit(Op::Equal);else if(o=="!=")emit(Op::NotEqual);else if(o=="===")emit(Op::StrictEqual);else if(o=="!==")emit(Op::StrictNotEqual);else if(o=="<")emit(Op::Less);else if(o=="<=")emit(Op::LessEqual);else if(o==">")emit(Op::Greater);else if(o==">=")emit(Op::GreaterEqual);else{error="unsupported binary operator";return false;}return true;}
bool compile(const Program&p,Bytecode&b,std::string&error){std::unordered_set<std::string>names;for(std::size_t i=0;i<p.statements.size();++i){const auto&s=p.statements[i];if(s.kind==StatementKind::Declaration&&!names.insert(s.name).second){error="duplicate binding '"+s.name+"'";return false;}if(!expression(*s.expression,b,error))return false;if(s.kind==StatementKind::Declaration){b.instructions.push_back({Op::Store,0,false,s.name});b.instructions.push_back({Op::PushUndefined});}if(i+1<p.statements.size())b.instructions.push_back({Op::Pop});}if(p.statements.empty())b.instructions.push_back({Op::PushUndefined});return true;}
static const char*name(Op o){static const char*n[]={"push.undefined","push.null","push.boolean","push.number","push.string","load","store","unary.plus","negate","not","add","subtract","multiply","divide","remainder","equal","not.equal","strict.equal","strict.not.equal","less","less.equal","greater","greater.equal","pop"};return n[static_cast<int>(o)];}
std::string disassemble(const Bytecode&b){std::ostringstream out;for(std::size_t i=0;i<b.instructions.size();++i){const auto&x=b.instructions[i];out<<i<<" "<<name(x.op);if(x.op==Op::PushNumber)out<<" "<<x.number;else if(x.op==Op::PushBoolean)out<<" "<<(x.boolean?"true":"false");else if(!x.text.empty())out<<" "<<x.text;out<<"\n";}return out.str();}
}
