#include "Bytecode.h"
#include <sstream>
#include <unordered_set>
namespace jspp { namespace {
struct Loop { std::vector<std::size_t>breaks,continues; };
struct Compiler {
 Bytecode&b;std::string&error;std::unordered_set<std::string>names;std::vector<Loop>loops;
 Compiler(Bytecode&code,std::string&message):b(code),error(message){}
 std::size_t emit(Op op){b.instructions.push_back({op});return b.instructions.size()-1;}
 void patch(std::size_t at,std::size_t target){b.instructions[at].target=target;}
 bool expr(const Expr&e){switch(e.kind){case ExprKind::Number:b.instructions.push_back({Op::PushNumber,e.number});return true;case ExprKind::String:b.instructions.push_back({Op::PushString,0,false,e.text});return true;case ExprKind::Boolean:b.instructions.push_back({Op::PushBoolean,0,e.text=="true"});return true;case ExprKind::Null:emit(Op::PushNull);return true;case ExprKind::Undefined:emit(Op::PushUndefined);return true;case ExprKind::Identifier:b.instructions.push_back({Op::Load,0,false,e.text});return true;case ExprKind::Unary:if(!expr(*e.right))return false;if(e.text=="+")emit(Op::UnaryPlus);else if(e.text=="-")emit(Op::Negate);else emit(Op::Not);return true;case ExprKind::Assignment:if(!expr(*e.right))return false;b.instructions.push_back({Op::Store,0,false,e.text});return true;case ExprKind::Conditional:{if(!expr(*e.left))return false;auto no=emit(Op::JumpIfFalse);if(!expr(*e.right))return false;auto end=emit(Op::Jump);patch(no,b.instructions.size());if(!expr(*e.third))return false;patch(end,b.instructions.size());return true;}case ExprKind::Binary:break;}
  if(e.text=="&&"||e.text=="||"){if(!expr(*e.left))return false;emit(Op::Duplicate);auto done=emit(e.text=="&&"?Op::JumpIfFalse:Op::JumpIfTrue);emit(Op::Pop);if(!expr(*e.right))return false;patch(done,b.instructions.size());return true;}
  if(!expr(*e.left)||!expr(*e.right))return false;
  const auto&o=e.text;if(o=="+")emit(Op::Add);else if(o=="-")emit(Op::Subtract);else if(o=="*")emit(Op::Multiply);else if(o=="/")emit(Op::Divide);else if(o=="%")emit(Op::Remainder);else if(o=="==")emit(Op::Equal);else if(o=="!=")emit(Op::NotEqual);else if(o=="===")emit(Op::StrictEqual);else if(o=="!==")emit(Op::StrictNotEqual);else if(o=="<")emit(Op::Less);else if(o=="<=")emit(Op::LessEqual);else if(o==">")emit(Op::Greater);else if(o==">=")emit(Op::GreaterEqual);else{error="unsupported binary operator";return false;}return true;
 }
 bool stmt(const Statement&s){switch(s.kind){case StatementKind::Empty:emit(Op::PushUndefined);return true;case StatementKind::Expression:return expr(*s.expression);case StatementKind::Declaration:if(!names.insert(s.name).second){error="duplicate binding '"+s.name+"'";return false;}if(!expr(*s.expression))return false;b.instructions.push_back({Op::Declare,0,s.constant,s.name});emit(Op::PushUndefined);return true;case StatementKind::Block:if(s.body.empty()){emit(Op::PushUndefined);return true;}for(std::size_t i=0;i<s.body.size();++i){if(!stmt(s.body[i]))return false;if(i+1<s.body.size())emit(Op::Pop);}return true;case StatementKind::If:{if(!expr(*s.condition))return false;auto otherwise=emit(Op::JumpIfFalse);if(!stmt(*s.then_branch))return false;auto done=emit(Op::Jump);patch(otherwise,b.instructions.size());if(s.else_branch){if(!stmt(*s.else_branch))return false;}else emit(Op::PushUndefined);patch(done,b.instructions.size());return true;}case StatementKind::While:{const auto condition=b.instructions.size();if(!expr(*s.condition))return false;auto done=emit(Op::JumpIfFalse);loops.push_back({});if(!stmt(*s.then_branch))return false;emit(Op::Pop);for(auto x:loops.back().continues)patch(x,condition);b.instructions.push_back({Op::Jump,0,false,{},condition});const auto end=b.instructions.size();patch(done,end);for(auto x:loops.back().breaks)patch(x,end);loops.pop_back();emit(Op::PushUndefined);return true;}case StatementKind::For:{if(s.initializer){if(!stmt(*s.initializer))return false;emit(Op::Pop);}const auto condition=b.instructions.size();if(s.condition){if(!expr(*s.condition))return false;}else b.instructions.push_back({Op::PushBoolean,0,true});auto done=emit(Op::JumpIfFalse);loops.push_back({});if(!stmt(*s.then_branch))return false;emit(Op::Pop);const auto update=b.instructions.size();for(auto x:loops.back().continues)patch(x,update);if(s.update){if(!expr(*s.update))return false;emit(Op::Pop);}b.instructions.push_back({Op::Jump,0,false,{},condition});const auto end=b.instructions.size();patch(done,end);for(auto x:loops.back().breaks)patch(x,end);loops.pop_back();emit(Op::PushUndefined);return true;}case StatementKind::Break:if(loops.empty()){error="break outside loop";return false;}loops.back().breaks.push_back(emit(Op::Jump));return true;case StatementKind::Continue:if(loops.empty()){error="continue outside loop";return false;}loops.back().continues.push_back(emit(Op::Jump));return true;}return false;}
}; }
bool compile(const Program&p,Bytecode&b,std::string&error){Compiler c{b,error};for(std::size_t i=0;i<p.statements.size();++i){if(!c.stmt(p.statements[i]))return false;if(i+1<p.statements.size())c.emit(Op::Pop);}if(p.statements.empty())c.emit(Op::PushUndefined);return true;}
static const char*name(Op o){static const char*n[]={"push.undefined","push.null","push.boolean","push.number","push.string","load","declare","store","unary.plus","negate","not","add","subtract","multiply","divide","remainder","equal","not.equal","strict.equal","strict.not.equal","less","less.equal","greater","greater.equal","pop","duplicate","jump","jump.if.false","jump.if.true"};return n[static_cast<int>(o)];}
std::string disassemble(const Bytecode&b){std::ostringstream out;for(std::size_t i=0;i<b.instructions.size();++i){const auto&x=b.instructions[i];out<<i<<" "<<name(x.op);if(x.op==Op::PushNumber)out<<" "<<x.number;else if(x.op==Op::PushBoolean)out<<" "<<(x.boolean?"true":"false");else if(!x.text.empty())out<<" "<<x.text;if(x.op==Op::Jump||x.op==Op::JumpIfFalse||x.op==Op::JumpIfTrue)out<<" -> "<<x.target;out<<"\n";}return out.str();}
}
