#include "VM.h"
#include <cmath>
#include <sstream>
namespace jspp { namespace {
bool truthy(const js_value&v){switch(v.kind){case JS_VALUE_UNDEFINED:case JS_VALUE_NULL:return false;case JS_VALUE_BOOLEAN:return v.boolean;case JS_VALUE_NUMBER:return v.number!=0&&!std::isnan(v.number);case JS_VALUE_STRING:return !v.string.empty();case JS_VALUE_FUNCTION:case JS_VALUE_OBJECT:case JS_VALUE_ARRAY:return true;}return false;}
bool equal(const js_value&a,const js_value&b,bool strict){if(a.kind==b.kind){if(a.kind==JS_VALUE_NUMBER)return a.number==b.number;if(a.kind==JS_VALUE_BOOLEAN)return a.boolean==b.boolean;if(a.kind==JS_VALUE_STRING)return a.string==b.string;if(a.kind==JS_VALUE_FUNCTION)return a.function==b.function;if(a.kind==JS_VALUE_OBJECT)return a.object==b.object;if(a.kind==JS_VALUE_ARRAY)return a.array==b.array;return true;}return !strict&&((a.kind==JS_VALUE_NULL&&b.kind==JS_VALUE_UNDEFINED)||(a.kind==JS_VALUE_UNDEFINED&&b.kind==JS_VALUE_NULL));}
bool key(const js_value&v,std::string&out){if(v.kind==JS_VALUE_STRING){out=v.string;return true;}if(v.kind==JS_VALUE_NUMBER&&std::isfinite(v.number)){std::ostringstream s;s<<v.number;out=s.str();return true;}return false;}
bool index(const js_value&v,std::size_t&out){if(v.kind!=JS_VALUE_NUMBER||v.number<0||!std::isfinite(v.number)||std::floor(v.number)!=v.number)return false;out=static_cast<std::size_t>(v.number);return true;}
Binding*find(const std::shared_ptr<Environment>&env,const std::string&name){for(auto at=env;at;at=at->parent){auto it=at->bindings.find(name);if(it!=at->bindings.end())return &it->second;}return nullptr;}
bool run(const Bytecode&code,std::shared_ptr<Environment>env,js_value&result,std::string&error,std::size_t&budget,std::size_t depth){
 if(depth>512){error="call stack limit exceeded";return false;}std::vector<js_value>stack;auto pop=[&](){auto v=std::move(stack.back());stack.pop_back();return v;};std::size_t pc=0;
 while(pc<code.instructions.size()){
  if(budget--==0){error="execution limit exceeded";return false;}const auto&i=code.instructions[pc++];
  switch(i.op){case Op::PushUndefined:stack.push_back({});break;case Op::PushNull:{js_value v;v.kind=JS_VALUE_NULL;stack.push_back(std::move(v));break;}case Op::PushBoolean:{js_value v;v.kind=JS_VALUE_BOOLEAN;v.boolean=i.boolean;stack.push_back(std::move(v));break;}case Op::PushNumber:{js_value v;v.kind=JS_VALUE_NUMBER;v.number=i.number;stack.push_back(std::move(v));break;}case Op::PushString:{js_value v;v.kind=JS_VALUE_STRING;v.string=i.text;stack.push_back(std::move(v));break;}
   case Op::Load:{auto*v=find(env,i.text);if(!v){error="unknown identifier '"+i.text+"'";return false;}stack.push_back(v->value);break;}
   case Op::Declare:if(stack.empty()){error="invalid bytecode stack";return false;}env->bindings[i.text]={pop(),i.boolean};break;
   case Op::Store:{if(stack.empty()){error="invalid bytecode stack";return false;}auto*v=find(env,i.text);if(!v){error="unknown identifier '"+i.text+"'";return false;}if(v->constant){error="assignment to constant '"+i.text+"'";return false;}v->value=stack.back();break;}
   case Op::EnterScope:{auto child=std::make_shared<Environment>();child->parent=env;env=std::move(child);break;}case Op::LeaveScope:if(!env->parent){error="invalid scope bytecode";return false;}env=env->parent;break;
   case Op::MakeFunction:{if(i.target>=code.functions.size()){error="invalid function bytecode";return false;}js_value v;v.kind=JS_VALUE_FUNCTION;v.function=std::make_shared<FunctionObject>();v.function->prototype=code.functions[i.target];v.function->closure=env;stack.push_back(std::move(v));break;}
   case Op::Call:{if(stack.size()<i.target+1){error="invalid call stack";return false;}std::vector<js_value>args(i.target);for(std::size_t n=i.target;n>0;--n)args[n-1]=pop();auto callee=pop();if(callee.kind!=JS_VALUE_FUNCTION||!callee.function){error="value is not callable";return false;}auto call_env=std::make_shared<Environment>();call_env->parent=callee.function->closure;const auto&p=*callee.function->prototype;for(std::size_t n=0;n<p.parameters.size();++n)call_env->bindings[p.parameters[n]]={n<args.size()?args[n]:js_value{},false};js_value value;if(!run(*p.code,call_env,value,error,budget,depth+1))return false;stack.push_back(std::move(value));break;}
   case Op::Return:if(stack.empty()){error="invalid return stack";return false;}result=pop();return true;
   case Op::MakeObject:{js_value v;v.kind=JS_VALUE_OBJECT;v.object=std::make_shared<ObjectValue>();stack.push_back(std::move(v));break;}
   case Op::MakeArray:{js_value v;v.kind=JS_VALUE_ARRAY;v.array=std::make_shared<ArrayValue>();stack.push_back(std::move(v));break;}
   case Op::DefineProperty:{if(stack.size()<3){error="invalid property stack";return false;}auto value=pop(),property=pop();std::string name;if(!key(property,name)){error="property key must be a string or number";return false;}auto&object=stack.back();if(object.kind!=JS_VALUE_OBJECT||!object.object){error="property definition requires an object";return false;}object.object->properties[name]=std::move(value);break;}
   case Op::ArrayPush:{if(stack.size()<2){error="invalid array stack";return false;}auto value=pop();auto&array=stack.back();if(array.kind!=JS_VALUE_ARRAY||!array.array){error="array append requires an array";return false;}array.array->elements.push_back(std::move(value));break;}
   case Op::GetProperty:{if(stack.size()<2){error="invalid property stack";return false;}auto property=pop(),object=pop(),value=js_value{};std::string name;if(object.kind==JS_VALUE_ARRAY&&object.array){std::size_t at=0;if(index(property,at)){if(at<object.array->elements.size())value=object.array->elements[at];}else{if(!key(property,name)){error="property key must be a string or number";return false;}if(name=="length"){value.kind=JS_VALUE_NUMBER;value.number=static_cast<double>(object.array->elements.size());}else{auto found=object.array->properties.find(name);if(found!=object.array->properties.end())value=found->second;}}}else if(object.kind==JS_VALUE_OBJECT&&object.object){if(!key(property,name)){error="property key must be a string or number";return false;}auto found=object.object->properties.find(name);if(found!=object.object->properties.end())value=found->second;}else{error="property access requires an object or array";return false;}stack.push_back(std::move(value));break;}
   case Op::SetProperty:{if(stack.size()<3){error="invalid property stack";return false;}auto value=pop(),property=pop(),object=pop();std::string name;if(object.kind==JS_VALUE_ARRAY&&object.array){std::size_t at=0;if(index(property,at)){if(at>=object.array->elements.size())object.array->elements.resize(at+1);object.array->elements[at]=value;}else{if(!key(property,name)){error="property key must be a string or number";return false;}if(name=="length"){error="array length assignment is not supported";return false;}object.array->properties[name]=value;}}else if(object.kind==JS_VALUE_OBJECT&&object.object){if(!key(property,name)){error="property key must be a string or number";return false;}object.object->properties[name]=value;}else{error="property assignment requires an object or array";return false;}stack.push_back(std::move(value));break;}
   case Op::Pop:if(!stack.empty())stack.pop_back();break;case Op::Duplicate:if(stack.empty()){error="invalid bytecode stack";return false;}stack.push_back(stack.back());break;
   case Op::Jump:pc=i.target;break;case Op::JumpIfFalse:case Op::JumpIfTrue:{if(stack.empty()){error="invalid bytecode stack";return false;}bool yes=truthy(pop());if((i.op==Op::JumpIfTrue&&yes)||(i.op==Op::JumpIfFalse&&!yes))pc=i.target;break;}
   case Op::UnaryPlus:case Op::Negate:{if(stack.empty()){error="invalid bytecode stack";return false;}auto v=pop();if(v.kind!=JS_VALUE_NUMBER){error="numeric unary operator requires a number";return false;}if(i.op==Op::Negate)v.number=-v.number;stack.push_back(std::move(v));break;}case Op::Not:{if(stack.empty()){error="invalid bytecode stack";return false;}auto v=pop();js_value x;x.kind=JS_VALUE_BOOLEAN;x.boolean=!truthy(v);stack.push_back(std::move(x));break;}
   default:{if(stack.size()<2){error="invalid bytecode stack";return false;}auto right=pop(),left=pop(),out=js_value{};if(i.op==Op::Add&&left.kind==JS_VALUE_STRING&&right.kind==JS_VALUE_STRING){out.kind=JS_VALUE_STRING;out.string=left.string+right.string;stack.push_back(std::move(out));break;}if(i.op==Op::Equal||i.op==Op::NotEqual||i.op==Op::StrictEqual||i.op==Op::StrictNotEqual){out.kind=JS_VALUE_BOOLEAN;out.boolean=equal(left,right,i.op==Op::StrictEqual||i.op==Op::StrictNotEqual);if(i.op==Op::NotEqual||i.op==Op::StrictNotEqual)out.boolean=!out.boolean;stack.push_back(std::move(out));break;}if(i.op==Op::Less||i.op==Op::LessEqual||i.op==Op::Greater||i.op==Op::GreaterEqual){out.kind=JS_VALUE_BOOLEAN;if(left.kind==JS_VALUE_NUMBER&&right.kind==JS_VALUE_NUMBER){if(i.op==Op::Less)out.boolean=left.number<right.number;else if(i.op==Op::LessEqual)out.boolean=left.number<=right.number;else if(i.op==Op::Greater)out.boolean=left.number>right.number;else out.boolean=left.number>=right.number;}else if(left.kind==JS_VALUE_STRING&&right.kind==JS_VALUE_STRING){if(i.op==Op::Less)out.boolean=left.string<right.string;else if(i.op==Op::LessEqual)out.boolean=left.string<=right.string;else if(i.op==Op::Greater)out.boolean=left.string>right.string;else out.boolean=left.string>=right.string;}else{error="ordering requires two numbers or two strings";return false;}stack.push_back(std::move(out));break;}if(left.kind!=JS_VALUE_NUMBER||right.kind!=JS_VALUE_NUMBER){error="arithmetic requires two numbers (or two strings for '+')";return false;}out.kind=JS_VALUE_NUMBER;if(i.op==Op::Add)out.number=left.number+right.number;else if(i.op==Op::Subtract)out.number=left.number-right.number;else if(i.op==Op::Multiply)out.number=left.number*right.number;else if(i.op==Op::Divide)out.number=left.number/right.number;else if(i.op==Op::Remainder)out.number=std::fmod(left.number,right.number);else{error="invalid arithmetic opcode";return false;}stack.push_back(std::move(out));break;}
  }
 }
 if(stack.size()!=1){error="invalid bytecode completion stack";return false;}result=std::move(stack.back());return true;
}
}
bool execute(const Bytecode&code,js_value&result,std::string&error,std::size_t budget){return run(code,std::make_shared<Environment>(),result,error,budget,0);}
}
