#include "VM.h"
#include <cmath>
#include <sstream>
namespace jspp { namespace {
bool truthy(const js_value&v){switch(v.kind){case JS_VALUE_UNDEFINED:case JS_VALUE_NULL:return false;case JS_VALUE_BOOLEAN:return v.boolean;case JS_VALUE_NUMBER:return v.number!=0&&!std::isnan(v.number);case JS_VALUE_STRING:return !v.string.empty();case JS_VALUE_FUNCTION:case JS_VALUE_OBJECT:case JS_VALUE_ARRAY:return true;}return false;}
bool equal(const js_value&a,const js_value&b,bool strict){if(a.kind==b.kind){if(a.kind==JS_VALUE_NUMBER)return a.number==b.number;if(a.kind==JS_VALUE_BOOLEAN)return a.boolean==b.boolean;if(a.kind==JS_VALUE_STRING)return a.string==b.string;if(a.kind==JS_VALUE_FUNCTION)return a.function==b.function;if(a.kind==JS_VALUE_OBJECT)return a.object==b.object;if(a.kind==JS_VALUE_ARRAY)return a.array==b.array;return true;}return !strict&&((a.kind==JS_VALUE_NULL&&b.kind==JS_VALUE_UNDEFINED)||(a.kind==JS_VALUE_UNDEFINED&&b.kind==JS_VALUE_NULL));}
bool key(const js_value&v,std::string&out){if(v.kind==JS_VALUE_STRING){out=v.string;return true;}if(v.kind==JS_VALUE_NUMBER&&std::isfinite(v.number)){std::ostringstream s;s<<v.number;out=s.str();return true;}return false;}
bool index(const js_value&v,std::size_t&out){if(v.kind!=JS_VALUE_NUMBER||v.number<0||!std::isfinite(v.number)||std::floor(v.number)!=v.number)return false;out=static_cast<std::size_t>(v.number);return true;}
bool lookup(const std::shared_ptr<ObjectValue>&object,const std::string&name,js_value&value){for(auto at=object;at;at=at->prototype){auto found=at->properties.find(name);if(found!=at->properties.end()){value=found->second;return true;}}return false;}
std::string display(const js_value&v){std::ostringstream out;switch(v.kind){case JS_VALUE_UNDEFINED:return "undefined";case JS_VALUE_NULL:return "null";case JS_VALUE_BOOLEAN:return v.boolean?"true":"false";case JS_VALUE_NUMBER:out<<v.number;return out.str();case JS_VALUE_STRING:return v.string;case JS_VALUE_FUNCTION:return "[function]";case JS_VALUE_OBJECT:return "[object Object]";case JS_VALUE_ARRAY:return "[array]";}return "undefined";}
Binding*find(const std::shared_ptr<Environment>&env,const std::string&name){for(auto at=env;at;at=at->parent){auto it=at->bindings.find(name);if(it!=at->bindings.end())return &it->second;}return nullptr;}
bool run(const Bytecode&code,std::shared_ptr<Environment>env,js_value&result,Completion&completion,std::string&error,std::size_t&budget,std::size_t depth,Heap&heap){
 if(depth>512){error="call stack limit exceeded";return false;}std::vector<js_value>stack;auto pop=[&](){auto v=std::move(stack.back());stack.pop_back();return v;};auto invoke=[&](const js_value&callee,const std::vector<js_value>&args,const js_value&receiver,js_value&value){if(callee.kind!=JS_VALUE_FUNCTION||!callee.function){error="value is not callable";return false;}auto call_env=heap.environment();call_env->parent=callee.function->closure;call_env->bindings["this"]={receiver,true};const auto&p=*callee.function->prototype;for(std::size_t n=0;n<p.parameters.size();++n)call_env->bindings[p.parameters[n]]={n<args.size()?args[n]:js_value{},false};Completion child;if(!run(*p.code,call_env,value,child,error,budget,depth+1,heap)){if(child.kind==CompletionKind::Throw)completion=std::move(child);return false;}return true;};std::size_t pc=0;
 while(pc<code.instructions.size()){
  if(depth==0&&heap.collection_due())heap.collect(stack,{env});
  if(budget--==0){error="execution limit exceeded";return false;}const auto&i=code.instructions[pc++];
  switch(i.op){case Op::PushUndefined:stack.push_back({});break;case Op::PushNull:{js_value v;v.kind=JS_VALUE_NULL;stack.push_back(std::move(v));break;}case Op::PushBoolean:{js_value v;v.kind=JS_VALUE_BOOLEAN;v.boolean=i.boolean;stack.push_back(std::move(v));break;}case Op::PushNumber:{js_value v;v.kind=JS_VALUE_NUMBER;v.number=i.number;stack.push_back(std::move(v));break;}case Op::PushString:{js_value v;v.kind=JS_VALUE_STRING;v.string=i.text;stack.push_back(std::move(v));break;}
   case Op::Load:{auto*v=find(env,i.text);if(!v){error="unknown identifier '"+i.text+"'";return false;}stack.push_back(v->value);break;}
   case Op::Declare:if(stack.empty()){error="invalid bytecode stack";return false;}env->bindings[i.text]={pop(),i.boolean};break;
   case Op::Store:{if(stack.empty()){error="invalid bytecode stack";return false;}auto*v=find(env,i.text);if(!v){error="unknown identifier '"+i.text+"'";return false;}if(v->constant){error="assignment to constant '"+i.text+"'";return false;}v->value=stack.back();break;}
   case Op::EnterScope:{auto child=heap.environment();child->parent=env;env=std::move(child);break;}case Op::LeaveScope:if(!env->parent){error="invalid scope bytecode";return false;}env=env->parent;break;
   case Op::MakeFunction:{if(i.target>=code.functions.size()){error="invalid function bytecode";return false;}js_value v;v.kind=JS_VALUE_FUNCTION;v.function=heap.function();v.function->prototype=code.functions[i.target];v.function->closure=env;v.function->instance_prototype=heap.object();stack.push_back(std::move(v));break;}
   case Op::Call:{if(stack.size()<i.target+1){error="invalid call stack";return false;}std::vector<js_value>args(i.target);for(std::size_t n=i.target;n>0;--n)args[n-1]=pop();auto callee=pop(),receiver=js_value{},value=js_value{};if(!invoke(callee,args,receiver,value))return false;stack.push_back(std::move(value));break;}
   case Op::CallMethod:{if(stack.size()<i.target+2){error="invalid method call stack";return false;}std::vector<js_value>args(i.target);for(std::size_t n=i.target;n>0;--n)args[n-1]=pop();auto property=pop(),receiver=pop(),callee=js_value{};std::string name;if(!key(property,name)){error="property key must be a string or number";return false;}if(receiver.kind==JS_VALUE_OBJECT&&receiver.object)lookup(receiver.object,name,callee);else if(receiver.kind==JS_VALUE_ARRAY&&receiver.array){auto found=receiver.array->properties.find(name);if(found!=receiver.array->properties.end())callee=found->second;else lookup(receiver.array->prototype,name,callee);}else{error="method call requires an object or array";return false;}js_value value;if(!invoke(callee,args,receiver,value))return false;stack.push_back(std::move(value));break;}
   case Op::Construct:{if(stack.size()<i.target+1){error="invalid construct stack";return false;}std::vector<js_value>args(i.target);for(std::size_t n=i.target;n>0;--n)args[n-1]=pop();auto callee=pop();if(callee.kind!=JS_VALUE_FUNCTION||!callee.function){error="value is not a constructor";return false;}js_value receiver;receiver.kind=JS_VALUE_OBJECT;receiver.object=heap.object();receiver.object->prototype=callee.function->instance_prototype;js_value value;if(!invoke(callee,args,receiver,value))return false;if(value.kind==JS_VALUE_OBJECT||value.kind==JS_VALUE_ARRAY||value.kind==JS_VALUE_FUNCTION)stack.push_back(std::move(value));else stack.push_back(std::move(receiver));break;}
   case Op::Return:if(stack.empty()){error="invalid return stack";return false;}result=pop();completion.kind=CompletionKind::Return;completion.value=result;return true;
   case Op::Throw:if(stack.empty()){error="invalid throw stack";return false;}completion.kind=CompletionKind::Throw;completion.value=pop();return false;
   case Op::MakeObject:{js_value v;v.kind=JS_VALUE_OBJECT;v.object=heap.object();stack.push_back(std::move(v));break;}
   case Op::MakeArray:{js_value v;v.kind=JS_VALUE_ARRAY;v.array=heap.array();stack.push_back(std::move(v));break;}
   case Op::DefineProperty:{if(stack.size()<3){error="invalid property stack";return false;}auto value=pop(),property=pop();std::string name;if(!key(property,name)){error="property key must be a string or number";return false;}auto&object=stack.back();if(object.kind!=JS_VALUE_OBJECT||!object.object){error="property definition requires an object";return false;}object.object->properties[name]=std::move(value);break;}
   case Op::ArrayPush:{if(stack.size()<2){error="invalid array stack";return false;}auto value=pop();auto&array=stack.back();if(array.kind!=JS_VALUE_ARRAY||!array.array){error="array append requires an array";return false;}array.array->elements.push_back(std::move(value));break;}
   case Op::GetProperty:{if(stack.size()<2){error="invalid property stack";return false;}auto property=pop(),object=pop(),value=js_value{};std::string name;if(object.kind==JS_VALUE_ARRAY&&object.array){std::size_t at=0;if(index(property,at)){if(at<object.array->elements.size())value=object.array->elements[at];}else{if(!key(property,name)){error="property key must be a string or number";return false;}if(name=="length"){value.kind=JS_VALUE_NUMBER;value.number=static_cast<double>(object.array->elements.size());}else{auto found=object.array->properties.find(name);if(found!=object.array->properties.end())value=found->second;else lookup(object.array->prototype,name,value);}}}else if(object.kind==JS_VALUE_OBJECT&&object.object){if(!key(property,name)){error="property key must be a string or number";return false;}lookup(object.object,name,value);}else if(object.kind==JS_VALUE_FUNCTION&&object.function){if(!key(property,name)){error="property key must be a string or number";return false;}if(name=="prototype"){value.kind=JS_VALUE_OBJECT;value.object=object.function->instance_prototype;}else{auto found=object.function->properties.find(name);if(found!=object.function->properties.end())value=found->second;}}else{error="property access requires an object, array or function";return false;}stack.push_back(std::move(value));break;}
   case Op::SetProperty:{if(stack.size()<3){error="invalid property stack";return false;}auto value=pop(),property=pop(),object=pop();std::string name;if(object.kind==JS_VALUE_ARRAY&&object.array){std::size_t at=0;if(index(property,at)){if(at>=object.array->elements.size())object.array->elements.resize(at+1);object.array->elements[at]=value;}else{if(!key(property,name)){error="property key must be a string or number";return false;}if(name=="length"){error="array length assignment is not supported";return false;}object.array->properties[name]=value;}}else if(object.kind==JS_VALUE_OBJECT&&object.object){if(!key(property,name)){error="property key must be a string or number";return false;}object.object->properties[name]=value;}else if(object.kind==JS_VALUE_FUNCTION&&object.function){if(!key(property,name)){error="property key must be a string or number";return false;}if(name=="prototype"){if(value.kind!=JS_VALUE_OBJECT||!value.object){error="function prototype must be an object";return false;}object.function->instance_prototype=value.object;}else object.function->properties[name]=value;}else{error="property assignment requires an object, array or function";return false;}stack.push_back(std::move(value));break;}
   case Op::Pop:if(!stack.empty())stack.pop_back();break;case Op::Duplicate:if(stack.empty()){error="invalid bytecode stack";return false;}stack.push_back(stack.back());break;
   case Op::Jump:pc=i.target;break;case Op::JumpIfFalse:case Op::JumpIfTrue:{if(stack.empty()){error="invalid bytecode stack";return false;}bool yes=truthy(pop());if((i.op==Op::JumpIfTrue&&yes)||(i.op==Op::JumpIfFalse&&!yes))pc=i.target;break;}
   case Op::UnaryPlus:case Op::Negate:{if(stack.empty()){error="invalid bytecode stack";return false;}auto v=pop();if(v.kind!=JS_VALUE_NUMBER){error="numeric unary operator requires a number";return false;}if(i.op==Op::Negate)v.number=-v.number;stack.push_back(std::move(v));break;}case Op::Not:{if(stack.empty()){error="invalid bytecode stack";return false;}auto v=pop();js_value x;x.kind=JS_VALUE_BOOLEAN;x.boolean=!truthy(v);stack.push_back(std::move(x));break;}
   default:{if(stack.size()<2){error="invalid bytecode stack";return false;}auto right=pop(),left=pop(),out=js_value{};if(i.op==Op::Add&&left.kind==JS_VALUE_STRING&&right.kind==JS_VALUE_STRING){out.kind=JS_VALUE_STRING;out.string=left.string+right.string;stack.push_back(std::move(out));break;}if(i.op==Op::Equal||i.op==Op::NotEqual||i.op==Op::StrictEqual||i.op==Op::StrictNotEqual){out.kind=JS_VALUE_BOOLEAN;out.boolean=equal(left,right,i.op==Op::StrictEqual||i.op==Op::StrictNotEqual);if(i.op==Op::NotEqual||i.op==Op::StrictNotEqual)out.boolean=!out.boolean;stack.push_back(std::move(out));break;}if(i.op==Op::Less||i.op==Op::LessEqual||i.op==Op::Greater||i.op==Op::GreaterEqual){out.kind=JS_VALUE_BOOLEAN;if(left.kind==JS_VALUE_NUMBER&&right.kind==JS_VALUE_NUMBER){if(i.op==Op::Less)out.boolean=left.number<right.number;else if(i.op==Op::LessEqual)out.boolean=left.number<=right.number;else if(i.op==Op::Greater)out.boolean=left.number>right.number;else out.boolean=left.number>=right.number;}else if(left.kind==JS_VALUE_STRING&&right.kind==JS_VALUE_STRING){if(i.op==Op::Less)out.boolean=left.string<right.string;else if(i.op==Op::LessEqual)out.boolean=left.string<=right.string;else if(i.op==Op::Greater)out.boolean=left.string>right.string;else out.boolean=left.string>=right.string;}else{error="ordering requires two numbers or two strings";return false;}stack.push_back(std::move(out));break;}if(left.kind!=JS_VALUE_NUMBER||right.kind!=JS_VALUE_NUMBER){error="arithmetic requires two numbers (or two strings for '+')";return false;}out.kind=JS_VALUE_NUMBER;if(i.op==Op::Add)out.number=left.number+right.number;else if(i.op==Op::Subtract)out.number=left.number-right.number;else if(i.op==Op::Multiply)out.number=left.number*right.number;else if(i.op==Op::Divide)out.number=left.number/right.number;else if(i.op==Op::Remainder)out.number=std::fmod(left.number,right.number);else{error="invalid arithmetic opcode";return false;}stack.push_back(std::move(out));break;}
  }
 }
 if(stack.size()!=1){error="invalid bytecode completion stack";return false;}result=std::move(stack.back());completion.kind=CompletionKind::Normal;completion.value=result;return true;
}
}
bool execute_completion(const Bytecode&code,Completion&completion,std::string&error,std::size_t budget,Heap*provided){Heap local;auto&heap=provided?*provided:local;js_value result;if(!run(code,heap.environment(),result,completion,error,budget,0,heap)){if(completion.kind==CompletionKind::Throw)error="uncaught exception: "+display(completion.value);return false;}if(completion.kind==CompletionKind::Return){error="return escaped top-level execution";return false;}return true;}
bool execute(const Bytecode&code,js_value&result,std::string&error,std::size_t budget,Heap*provided){Completion completion;if(!execute_completion(code,completion,error,budget,provided))return false;result=std::move(completion.value);return true;}
}
